version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
  app:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    environment:
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      BINANCE_SECRET_KEY: ${BINANCE_SECRET_KEY}
      DATABASE_URL: postgresql://bot:bot@db:5432/trading
    depends_on:
      - db
    command: bash -c "python scripts/setup.py && pytest -vv"
