apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trading-bot-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trading-bot-binding
subjects:
- kind: ServiceAccount
  name: trading-bot
roleRef:
  kind: Role
  name: trading-bot-role
  apiGroup: rbac.authorization.k8s.io
